package com.moonsonglabs.daml.sandbox

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.nio.file.Files

class SandboxGeneratorTest {
    @Test
    fun `generates local canton jar recipe files`() {
        val root = Files.createTempDirectory("managed-canton-sandbox")
        val profile = SandboxDefaults.newProfile(root).apply {
            id = "test-sandbox"
            generatedPath = root.resolve(".canton-sandboxes/test-sandbox").toString()
            participants.add(SandboxDefaults.participant(2, portBase))
            bindings.add(ParticipantSyncBinding(participants[1].id, synchronizers[0].id, true))
            partyAllocations.add(PartyAllocation("Bob", participants[1].id, synchronizers[0].id))
        }

        val generated = SandboxGenerator().generate(profile)
        val conf = Files.readString(generated.localConfig)
        val bootstrap = Files.readString(generated.localBootstrap)
        val run = Files.readString(generated.localRunScript)

        assertTrue(conf.contains("sequencers {"))
        assertTrue(conf.contains("participants {"))
        assertTrue(conf.contains("issuer {"))
        assertTrue(conf.contains("investor {"))
        assertTrue(conf.contains("ledger-api      { address = \"0.0.0.0\", port = 5011 }") || conf.contains("ledger-api { address = \"0.0.0.0\" port = 5011 }"))
        assertTrue(conf.contains("http-ledger-api { address = \"0.0.0.0\", port = 7575 }"))
        assertTrue(conf.contains("http-ledger-api { address = \"0.0.0.0\", port = 7576 }"))

        assertTrue(bootstrap.contains("nodes.local.start()"))
        assertTrue(bootstrap.contains("bootstrap.synchronizer("))
        assertTrue(bootstrap.contains("synchronizerOwners = Seq(globalSequencer, globalMediator)"))
        assertTrue(bootstrap.contains("issuer.synchronizers.connect_local(globalSequencer, alias = \"global\")"))
        assertTrue(bootstrap.contains("issuer.parties.enable(\"Bank\", synchronizer = Some(\"global\"), synchronizeParticipants = Seq(issuer))"))
        assertTrue(bootstrap.contains("investor.parties.enable(\"Bob\", synchronizer = Some(\"global\"), synchronizeParticipants = Seq(investor))"))
        assertTrue(bootstrap.contains("=== sandbox ready ==="))

        assertTrue(run.contains("CANTON_JAR_DEFAULT="))
        assertTrue(run.contains("exec java -jar \"${'$'}CANTON_JAR\" daemon -c \"${'$'}CONF\" --bootstrap \"${'$'}BOOT\""))
        assertTrue(generated.localRunScript.toFile().canExecute())
        assertTrue("Docker Compose files should not be generated by the local-only sandbox feature.", !Files.exists(generated.root.resolve("docker/docker-compose.yaml")))
    }

    @Test
    fun `party allocations are generated against explicit synchronizers`() {
        val profile = SandboxDefaults.newProfile(Files.createTempDirectory("managed-canton-multi-sync")).apply {
            id = "multi-sync"
            synchronizers.add(SandboxDefaults.synchronizer(2, portBase))
            bindings.clear()
            bindings.add(ParticipantSyncBinding(participants[0].id, synchronizers[0].id, true))
            bindings.add(ParticipantSyncBinding(participants[0].id, synchronizers[1].id, true))
            partyAllocations.clear()
            partyAllocations.add(PartyAllocation("Bank", participants[0].id, synchronizers[0].id))
            partyAllocations.add(PartyAllocation("Bank", participants[0].id, synchronizers[1].id))
        }

        val allocationScript = SandboxGenerator().allocationScript(profile)

        assertTrue(allocationScript.contains("issuer.parties.enable(\"Bank\", synchronizer = Some(\"global\"), synchronizeParticipants = Seq(issuer))"))
        assertTrue(allocationScript.contains("issuer.parties.enable(\"Bank\", synchronizer = Some(\"sync2\"), synchronizeParticipants = Seq(issuer))"))
    }

    @Test
    fun `dar uploads are vetted on every connected synchronizer`() {
        val profile = SandboxDefaults.newProfile(Files.createTempDirectory("managed-canton-multi-sync-dars")).apply {
            id = "multi-sync-dars"
            synchronizers.add(SandboxDefaults.synchronizer(2, portBase))
            bindings.clear()
            bindings.add(ParticipantSyncBinding(participants[0].id, synchronizers[0].id, true))
            bindings.add(ParticipantSyncBinding(participants[0].id, synchronizers[1].id, true))
            darAssignments.add(DarAssignment("/tmp/example.dar", mutableListOf(participants[0].id)))
        }

        val uploadScript = SandboxGenerator().uploadScript(profile, emptyMap())

        assertTrue(uploadScript.contains("issuer.dars.upload(\"/tmp/example.dar\", synchronizerId = Some(issuer.synchronizers.id_of(\"global\")))"))
        assertTrue(uploadScript.contains("issuer.dars.upload(\"/tmp/example.dar\", synchronizerId = Some(issuer.synchronizers.id_of(\"sync2\")))"))
    }

    @Test
    fun `regenerating profile clears stale copied dars`() {
        val root = Files.createTempDirectory("managed-canton-dars-clean")
        val dar1 = Files.writeString(root.resolve("one.dar"), "one")
        val dar2 = Files.writeString(root.resolve("two.dar"), "two")
        val profile = SandboxDefaults.newProfile(root).apply {
            id = "dar-clean"
            generatedPath = root.resolve(".canton-sandboxes/dar-clean").toString()
            darAssignments.add(DarAssignment(dar1.toString(), mutableListOf(participants[0].id)))
        }

        val generator = SandboxGenerator()
        val first = generator.generate(profile)
        assertTrue(Files.exists(first.darsDir.resolve("one.dar")))

        profile.darAssignments.clear()
        profile.darAssignments.add(DarAssignment(dar2.toString(), mutableListOf(profile.participants[0].id)))
        val second = generator.generate(profile)

        assertTrue(!Files.exists(second.darsDir.resolve("one.dar")))
        assertTrue(Files.exists(second.darsDir.resolve("two.dar")))
    }

    @Test
    fun `default profile mirrors two participant recipe ports when second participant is added`() {
        val profile = SandboxDefaults.newProfile(null).apply {
            participants.add(SandboxDefaults.participant(2, portBase))
        }
        assertEquals("issuer", profile.participants[0].name)
        assertEquals(5011, profile.participants[0].ledgerPort)
        assertEquals(5012, profile.participants[0].adminPort)
        assertEquals(7575, profile.participants[0].jsonPort)
        assertEquals("investor", profile.participants[1].name)
        assertEquals(5021, profile.participants[1].ledgerPort)
        assertEquals(5022, profile.participants[1].adminPort)
        assertEquals(7576, profile.participants[1].jsonPort)
        assertEquals("global", profile.synchronizers[0].name)
        assertEquals(5001, profile.synchronizers[0].sequencer.publicPort)
        assertEquals(5002, profile.synchronizers[0].sequencer.adminPort)
        assertEquals(5202, profile.synchronizers[0].mediator.adminPort)
    }
}
