canton {
  features.enable-testing-commands = yes

  participants {
    p1 {
      admin-api {
        address = "0.0.0.0"
        port = 5012
      }
      ledger-api {
        address = "0.0.0.0"
        port = 5011
      }
      storage.type = memory
    }
    p2 {
      admin-api {
        address = "0.0.0.0"
        port = 5022
      }
      ledger-api {
        address = "0.0.0.0"
        port = 5021
      }
      storage.type = memory
    }
  }

  domains {
    local {
      public-api {
        address = "0.0.0.0"
        port = 5018
      }
      admin-api {
        address = "0.0.0.0"
        port = 5019
      }
      storage.type = memory
      init {
        domain-parameters {
          protocol-version = 7
        }
      }
    }
  }
}
