#!/usr/bin/env npx ts-node
/**
 * Canton API Generator
 *
 * Transforms auto-generated Daml JS bindings into a clean, developer-friendly API.
 *
 * Output Structure:
 *   core/primitives.ts  - Canton/Daml primitives (Party, ContractId, Time, etc.)
 *   core/interfaces.ts  - Generic financial interfaces (Keys, Quantity, Lock, etc.)
 *   core/index.ts       - Re-exports
 *   <project>-api.ts    - Project-specific workflows with clear function signatures
 *
 * Usage: npx ts-node generate-canton-api.ts <daml-js-dir> <output-dir> [project-name]
 */

import * as fs from 'fs';
import * as path from 'path';
import * as ts from 'typescript';

// === CONFIGURATION ===

interface WorkflowChoice {
  name: string;
  args: string;
  result: string;
  description: string;
}

interface WorkflowTemplate {
  name: string;
  modulePath: string;
  templateId: string;
  fields: Array<{ name: string; type: string; description: string }>;
  choices: WorkflowChoice[];
  description: string;
}

interface ParsedModule {
  domain: string;
  name: string;
  qualifiedName: string;
  templateId: string;
  fields: Array<{ name: string; type: string }>;
  choices: Array<{ name: string; args: string; result: string }>;
  isWorkflow: boolean;
  workflowType?: 'Request' | 'Proposal';
}

// === PRIMITIVES (Static - never change) ===

const PRIMITIVES = `// core/primitives.ts
// Canton/Daml Primitives - Project Independent
// DO NOT EDIT - Generated by generate-canton-api.ts

/**
 * Unique identifier for a party on the Canton ledger.
 * Parties represent participants (users, institutions, services) in the network.
 * @example "Alice::1220abc123"
 */
export type Party = string;

/**
 * Type-safe contract identifier.
 * The generic parameter ensures compile-time type checking when exercising choices.
 * @example const accountCid: ContractId<Account> = "00abc123" as ContractId<Account>;
 */
export type ContractId<T> = string & { readonly __contractType: T };

/**
 * Optional value wrapper - value may be null.
 */
export type Optional<T> = T | null;

/**
 * ISO 8601 timestamp string.
 * @example "2024-01-15T10:30:00Z"
 */
export type Time = string;

/**
 * ISO 8601 date string (YYYY-MM-DD).
 * @example "2024-01-15"
 */
export type Date = string;

/**
 * Decimal number as string to preserve arbitrary precision.
 * Use for financial amounts to avoid floating point errors.
 * @example "1000.50"
 */
export type Numeric = string;

/**
 * Integer number.
 */
export type Int = number;

/**
 * Text string.
 */
export type Text = string;

/**
 * Boolean value.
 */
export type Bool = boolean;

/**
 * Unit type - represents "no value".
 */
export type Unit = Record<string, never>;

/**
 * String-keyed map/dictionary.
 */
export type TextMap<V> = Record<string, V>;

/**
 * Set represented as array (Daml sets serialize as arrays).
 */
export type Set<T> = T[];

/**
 * Contract wrapper with ID and payload.
 */
export interface Contract<T> {
  contractId: ContractId<T>;
  payload: T;
  createdAt?: Time;
}

/**
 * Query result page for paginated queries.
 */
export interface Page<T> {
  contracts: Contract<T>[];
  offset?: string;
}

/**
 * Command to be submitted to the ledger.
 * Wraps the command type for type-safe submission.
 */
export interface Command<T> {
  templateId: string;
  choice?: string;
  contractId?: string;
  argument: unknown;
  _resultType?: T;
}

/**
 * Result of exercising a choice.
 */
export interface ExerciseResult<T> {
  exerciseResult: T;
  events: unknown[];
}
`;

// === GENERATOR CLASS ===

class CantonApiGenerator {
  private damlJsDir: string;
  private outputDir: string;
  private projectName: string;
  private aliasMap = new Map<string, string>();
  private modules: ParsedModule[] = [];
  private interfaces = new Map<string, string>();
  private workflowTemplates: WorkflowTemplate[] = [];

  constructor(damlJsDir: string, outputDir: string, projectName: string) {
    this.damlJsDir = damlJsDir;
    this.outputDir = outputDir;
    this.projectName = projectName;
  }

  generate(): void {
    console.log(`\n📦 Canton API Generator`);
    console.log(`   Source: ${this.damlJsDir}`);
    console.log(`   Output: ${this.outputDir}`);
    console.log(`   Project: ${this.projectName}\n`);

    // 1. Scan and parse all modules
    this.scanModules();

    // 2. Generate core files
    this.generateCorePrimitives();
    this.generateCoreInterfaces();
    this.generateCoreIndex();

    // 3. Generate project API
    this.generateProjectApi();

    console.log(`\n✅ Generation complete!`);
    console.log(`   Files created:`);
    console.log(`   - core/primitives.ts`);
    console.log(`   - core/interfaces.ts`);
    console.log(`   - core/index.ts`);
    console.log(`   - ${this.projectName}-api.ts\n`);
  }

  private scanModules(): void {
    const packages = fs.readdirSync(this.damlJsDir).filter(d => {
      const p = path.join(this.damlJsDir, d);
      return fs.statSync(p).isDirectory() && fs.existsSync(path.join(p, 'lib'));
    });

    console.log(`📂 Scanning ${packages.length} packages...`);

    for (const pkg of packages) {
      this.scanPackage(pkg);
    }

    console.log(`   Found ${this.modules.length} templates`);
    console.log(`   Found ${this.workflowTemplates.length} workflow templates`);
    console.log(`   Found ${this.interfaces.size} interfaces`);
  }

  private scanPackage(pkgName: string): void {
    const libDir = path.join(this.damlJsDir, pkgName, 'lib');
    if (!fs.existsSync(libDir)) return;

    this.scanDirectory(libDir, pkgName);
  }

  private scanDirectory(dir: string, pkgName: string): void {
    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        this.scanDirectory(fullPath, pkgName);
      } else if (entry.name === 'module.d.ts') {
        this.parseModuleFile(fullPath, pkgName);
      }
    }
  }

  private parseModuleFile(filePath: string, pkgName: string): void {
    const content = fs.readFileSync(filePath, 'utf-8');
    const sourceFile = ts.createSourceFile(filePath, content, ts.ScriptTarget.Latest, true);

    // Extract path from file location
    const relativePath = path.relative(path.join(this.damlJsDir, pkgName, 'lib'), filePath);
    const modulePath = path.dirname(relativePath).replace(/\//g, '.');

    // Check if this is a workflow
    const isWorkflow = modulePath.includes('Workflow');

    // Parse type declarations
    ts.forEachChild(sourceFile, (node) => {
      if (ts.isTypeAliasDeclaration(node)) {
        this.parseTypeAlias(node, modulePath, pkgName, isWorkflow);
      } else if (ts.isInterfaceDeclaration(node)) {
        this.parseInterface(node, modulePath, pkgName, isWorkflow);
      } else if (ts.isVariableStatement(node)) {
        this.parseTemplateVariable(node, modulePath, pkgName, content, isWorkflow);
      }
    });
  }

  private parseTypeAlias(node: ts.TypeAliasDeclaration, modulePath: string, pkgName: string, isWorkflow: boolean): void {
    const name = node.name.text;
    const typeText = node.type ? node.type.getText() : 'unknown';

    // Collect interfaces for core/interfaces.ts
    if (!isWorkflow && this.isFinanceInterface(name)) {
      this.interfaces.set(name, this.simplifyType(typeText));
    }
  }

  private parseInterface(node: ts.InterfaceDeclaration, modulePath: string, pkgName: string, isWorkflow: boolean): void {
    const name = node.name.text;

    // Skip internal interfaces
    if (name.endsWith('Interface') || name.includes('Companion')) return;

    const fields: Array<{ name: string; type: string }> = [];

    for (const member of node.members) {
      if (ts.isPropertySignature(member) && member.name) {
        const fieldName = member.name.getText();
        const fieldType = member.type ? this.simplifyType(member.type.getText()) : 'unknown';
        fields.push({ name: fieldName, type: fieldType });
      }
    }

    if (fields.length > 0 && this.isFinanceInterface(name)) {
      let interfaceStr = `export interface ${name} {\n`;
      for (const f of fields) {
        interfaceStr += `  ${f.name}: ${f.type};\n`;
      }
      interfaceStr += `}`;
      this.interfaces.set(name, interfaceStr);
    }
  }

  private parseTemplateVariable(node: ts.VariableStatement, modulePath: string, pkgName: string, content: string, isWorkflow: boolean): void {
    for (const decl of node.declarationList.declarations) {
      if (!ts.isIdentifier(decl.name)) continue;

      const name = decl.name.text;
      const typeText = decl.type ? decl.type.getText() : '';

      // Check if this is a template
      const templateMatch = typeText.match(/Template<([^,]+),.*'#([^']+)'/);
      if (!templateMatch) continue;

      const templateId = templateMatch[2];
      const fields = this.extractTemplateFields(content, name);
      const choices = this.extractTemplateChoices(content, name);

      const domain = this.extractDomain(modulePath);
      const qualifiedName = this.createUniqueQualifiedName(templateId, modulePath, name, isWorkflow);

      const module: ParsedModule = {
        domain,
        name,
        qualifiedName,
        templateId,
        fields,
        choices,
        isWorkflow,
        workflowType: name === 'Request' || name === 'Proposal' ? name : undefined
      };

      this.modules.push(module);

      // If workflow, create WorkflowTemplate
      if (isWorkflow && (name === 'Request' || name === 'Proposal')) {
        this.workflowTemplates.push({
          name: modulePath.split('.').pop() || name,
          modulePath,
          templateId,
          fields: fields.map(f => ({ ...f, description: '' })),
          choices: choices.map(c => ({ ...c, description: this.getChoiceDescription(c.name) })),
          description: this.getWorkflowDescription(modulePath)
        });
      }
    }
  }

  private extractTemplateFields(content: string, templateName: string): Array<{ name: string; type: string }> {
    const fields: Array<{ name: string; type: string }> = [];

    // Match type declaration for template
    const typeRegex = new RegExp(`export declare type ${templateName} = \\{([^}]+)\\}`, 's');
    const match = content.match(typeRegex);

    if (match) {
      const fieldsStr = match[1];
      const fieldRegex = /(\w+):\s*([^;]+);/g;
      let fieldMatch;

      while ((fieldMatch = fieldRegex.exec(fieldsStr)) !== null) {
        fields.push({
          name: fieldMatch[1],
          type: this.simplifyType(fieldMatch[2].trim())
        });
      }
    }

    return fields;
  }

  private extractTemplateChoices(content: string, templateName: string): Array<{ name: string; args: string; result: string }> {
    const choices: Array<{ name: string; args: string; result: string }> = [];

    // Match interface declaration for choices
    const interfaceRegex = new RegExp(`export declare interface ${templateName}Interface \\{([^}]+)\\}`, 's');
    const match = content.match(interfaceRegex);

    if (match) {
      const interfaceStr = match[1];
      // Match each choice: ChoiceName: damlTypes.Choice<Template, Args, Result, ...>
      const choiceRegex = /(\w+):\s*damlTypes\.Choice<[^,]+,\s*([^,]+),\s*([^,>]+)/g;
      let choiceMatch;

      while ((choiceMatch = choiceRegex.exec(interfaceStr)) !== null) {
        const choiceName = choiceMatch[1];
        if (choiceName === 'Archive') continue; // Skip Archive, it's standard

        choices.push({
          name: choiceName,
          args: this.simplifyType(choiceMatch[2].trim()),
          result: this.simplifyComplexResult(choiceMatch[3].trim())
        });
      }
    }

    return choices;
  }

  private simplifyType(typeText: string): string {
    let result = typeText;

    // Remove package prefixes (pkg...)
    result = result.replace(/pkg[a-f0-9]+\./g, '');

    // Simplify common Daml Finance paths
    result = result.replace(/Daml\.Finance\.Interface\.Types\.Common\.V\d+\.Types\./g, '');
    result = result.replace(/Daml\.Finance\.Interface\.Settlement\.V\d+\.\w+\./g, '');
    result = result.replace(/Daml\.Finance\.Interface\.Holding\.V\d+\.\w+\./g, '');
    result = result.replace(/Daml\.Finance\.Interface\.Account\.V\d+\.\w+\./g, '');
    result = result.replace(/DA\.Types\./g, '');
    result = result.replace(/DA\.Internal\.Template\./g, '');

    // Replace damlTypes primitives
    result = result.replace(/damlTypes\.Party/g, 'Party');
    result = result.replace(/damlTypes\.ContractId/g, 'ContractId');
    result = result.replace(/damlTypes\.Numeric/g, 'Numeric');
    result = result.replace(/damlTypes\.Time/g, 'Time');
    result = result.replace(/damlTypes\.Date/g, 'Date');
    result = result.replace(/damlTypes\.Text/g, 'Text');
    result = result.replace(/damlTypes\.Int/g, 'Int');
    result = result.replace(/damlTypes\.Bool/g, 'Bool');
    result = result.replace(/damlTypes\.Optional/g, 'Optional');

    // Clean up arrays
    result = result.replace(/(\w+)\[\]/g, '$1[]');

    return result.trim();
  }

  private simplifyComplexResult(typeText: string): string {
    let result = this.simplifyType(typeText);

    // Handle Tuple types
    if (result.includes('Tuple3<')) {
      // Extract inner types and format nicely
      const tupleMatch = result.match(/Tuple3<([^>]+)>/);
      if (tupleMatch) {
        result = `[${tupleMatch[1]}]`;
      }
    }

    // Handle empty object
    if (result === '{}') {
      result = 'void';
    }

    return result;
  }

  private extractDomain(modulePath: string): string {
    const parts = modulePath.split('.');
    // Extract meaningful domain name
    if (parts.includes('Account')) return 'Account';
    if (parts.includes('Holding')) return 'Holding';
    if (parts.includes('Instrument')) return 'Instrument';
    if (parts.includes('Settlement')) return 'Settlement';
    if (parts.includes('Lifecycle')) return 'Lifecycle';
    if (parts.includes('Workflow')) return 'Workflow';
    return parts[parts.length - 1] || 'Other';
  }

  private createUniqueQualifiedName(templateId: string, modulePath: string, name: string, isWorkflow: boolean): string {
    if (isWorkflow) {
      // For workflows: Workflow_CreateAccount_Request
      return `${modulePath.replace(/\./g, '_')}_${name}`;
    }

    // Parse templateId to extract unique path
    // Format: "package:Module.Path:TemplateName"
    // Example: "daml-finance-lifecycle-v4:Daml.Finance.Lifecycle.V4.Event.Distribution:Event"
    const parts = templateId.split(':');
    if (parts.length >= 3) {
      const modulePathPart = parts[1]; // e.g., "Daml.Finance.Lifecycle.V4.Event.Distribution"
      const pathParts = modulePathPart.split('.');
      const domain = this.extractDomain(modulePath);

      // Get the subpath after V4 (or similar version marker)
      // For "Daml.Finance.Lifecycle.V4.Event.Distribution", extract "Event.Distribution"
      const versionIndex = pathParts.findIndex(p => /^V\d+$/.test(p));
      if (versionIndex !== -1 && versionIndex < pathParts.length - 1) {
        const subPath = pathParts.slice(versionIndex + 1); // Include all parts after version
        if (subPath.length > 1) {
          // Multiple subpath parts - use them all for uniqueness
          // e.g., Event.Distribution -> Event_Distribution_Event
          return `${domain}_${subPath.join('_')}_${name}`;
        }
        // Single subpath part - just domain_name
        return `${domain}_${name}`;
      }

      return `${domain}_${name}`;
    }

    return `${modulePath.replace(/\./g, '_')}_${name}`;
  }

  private isFinanceInterface(name: string): boolean {
    const coreInterfaces = [
      'AccountKey', 'InstrumentKey', 'HoldingFactoryKey', 'Quantity', 'Id',
      'Lock', 'Controllers', 'RoutedStep', 'Step', 'View', 'Hierarchy',
      'InstructionKey', 'BusinessDayAdjustment', 'Period', 'Frequency',
      'SchedulePeriod', 'PeriodicSchedule', 'DateOffset', 'HolidayCalendarData'
    ];
    return coreInterfaces.includes(name);
  }

  private getWorkflowDescription(modulePath: string): string {
    const descriptions: Record<string, string> = {
      'Workflow.CreateAccount': 'Request a new account from a custodian. The custodian can accept (creating the account) or decline.',
      'Workflow.DvP': 'Delivery-vs-Payment atomic swap. Exchange two assets atomically between counterparties.',
      'Workflow.Transfer': 'Request to transfer assets to another account. The asset owner must accept with the holding.',
      'Workflow.CreditAccount': 'Request to credit (mint) assets into an account. Typically used by issuers.'
    };
    return descriptions[modulePath] || `${modulePath} workflow`;
  }

  private getChoiceDescription(choiceName: string): string {
    const descriptions: Record<string, string> = {
      'Accept': 'Accept the request/proposal and execute the workflow',
      'Decline': 'Decline the request/proposal (counterparty action)',
      'Withdraw': 'Withdraw the request/proposal (requester/proposer action)'
    };
    return descriptions[choiceName] || `Execute ${choiceName}`;
  }

  private generateCorePrimitives(): void {
    const outputPath = path.join(this.outputDir, 'core', 'primitives.ts');
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, PRIMITIVES);
    console.log(`   ✓ core/primitives.ts`);
  }

  private generateCoreInterfaces(): void {
    let output = `// core/interfaces.ts
// Canton/Daml Finance Interfaces - Project Independent
// DO NOT EDIT - Generated by generate-canton-api.ts

import { Party, ContractId, Optional, Numeric, Time, TextMap, Set } from './primitives';

// ═══════════════════════════════════════════════════════════════
// IDENTIFIERS
// ═══════════════════════════════════════════════════════════════

/**
 * Generic identifier wrapper.
 * Wraps a string ID for type safety.
 */
export interface Id {
  unpack: string;
}

/**
 * Unique identifier for an account.
 * Combines custodian, owner, and account ID.
 */
export interface AccountKey {
  /** Party responsible for custody */
  custodian: Party;
  /** Beneficial owner of the account */
  owner: Party;
  /** Unique ID within custodian namespace */
  id: Id;
}

/**
 * Unique identifier for a financial instrument.
 * Instruments are versioned to support lifecycle events.
 */
export interface InstrumentKey {
  /** Party responsible for safekeeping */
  depository: Party;
  /** Party that issued the instrument */
  issuer: Party;
  /** Unique identifier (e.g., 'USD', 'AAPL') */
  id: Id;
  /** Version for lifecycle changes */
  version: string;
  /** Supported holding behaviors */
  holdingStandard: HoldingStandard;
}

/**
 * Unique identifier for a holding factory.
 */
export interface HoldingFactoryKey {
  provider: Party;
  id: Id;
}

/**
 * Unique identifier for a settlement instruction.
 */
export interface InstructionKey {
  instructor: Party;
  batchId: Id;
  id: Id;
}

// ═══════════════════════════════════════════════════════════════
// FINANCIAL TYPES
// ═══════════════════════════════════════════════════════════════

/**
 * Generic quantity with unit and amount.
 * The unit is typically an InstrumentKey for financial quantities.
 * @example { unit: usdInstrument, amount: "1000.00" }
 */
export interface Quantity<U = InstrumentKey, A = Numeric> {
  unit: U;
  amount: A;
}

/**
 * Account controller configuration.
 * Defines which parties can authorize debits and credits.
 */
export interface Controllers {
  /** Parties that can authorize outgoing transfers (debits) */
  outgoing: Set<Party>;
  /** Parties that can authorize incoming transfers (credits) */
  incoming: Set<Party>;
}

/**
 * Lock on a contract preventing certain operations.
 * Used during settlement for atomicity guarantees.
 */
export interface Lock {
  /** Parties holding the lock */
  lockers: Set<Party>;
  /** Context identifiers for the lock */
  context: Set<string>;
  /** Type of lock behavior */
  lockType: LockType;
}

/**
 * Settlement step with routing information.
 * Specifies sender, receiver, custodian, and quantity.
 */
export interface RoutedStep {
  sender: Party;
  receiver: Party;
  custodian: Party;
  quantity: Quantity;
}

/**
 * Settlement step without routing (custodian TBD).
 */
export interface Step {
  sender: Party;
  receiver: Party;
  quantity: Quantity;
}

/**
 * Custodian hierarchy for settlement routing.
 */
export interface Hierarchy {
  rootCustodian: Party;
  pathsToRootCustodian: Party[][];
}

// ═══════════════════════════════════════════════════════════════
// DATE/TIME TYPES
// ═══════════════════════════════════════════════════════════════

/**
 * Business day adjustment for date calculations.
 */
export interface BusinessDayAdjustment {
  calendarIds: string[];
  convention: BusinessDayConventionEnum;
}

/**
 * Holiday calendar definition.
 */
export interface HolidayCalendarData {
  id: string;
  weekend: DayOfWeek[];
  holidays: string[];
}

/**
 * Date offset for schedule calculations.
 */
export interface DateOffset {
  period: PeriodEnum;
  periodMultiplier: number;
  dayType: Optional<DayTypeEnum>;
  businessDayConvention: BusinessDayConventionEnum;
  businessCenters: string[];
}

/**
 * Time period definition.
 */
export interface Period {
  period: PeriodEnum;
  periodMultiplier: number;
}

/**
 * Schedule frequency with roll convention.
 */
export interface Frequency {
  period: Period;
  rollConvention: RollConventionEnum;
}

/**
 * Single period in a schedule.
 */
export interface SchedulePeriod {
  adjustedEndDate: string;
  adjustedStartDate: string;
  unadjustedEndDate: string;
  unadjustedStartDate: string;
  stubType: Optional<StubPeriodTypeEnum>;
}

/**
 * Periodic schedule definition.
 */
export interface PeriodicSchedule {
  effectiveDate: string;
  terminationDate: string;
  firstRegularPeriodStartDate: Optional<string>;
  lastRegularPeriodEndDate: Optional<string>;
  frequency: Frequency;
  businessDayAdjustment: BusinessDayAdjustment;
  effectiveDateBusinessDayAdjustment: Optional<BusinessDayAdjustment>;
  terminationDateBusinessDayAdjustment: Optional<BusinessDayAdjustment>;
  stubPeriodType: Optional<StubPeriodTypeEnum>;
}

// ═══════════════════════════════════════════════════════════════
// ENUMS (Opaque types - actual values depend on Daml model)
// ═══════════════════════════════════════════════════════════════

export type HoldingStandard = { tag: string; value?: unknown };
export type LockType = { tag: string; value?: unknown };
export type Allocation = { tag: string; value?: unknown };
export type Approval = { tag: string; value?: unknown };
export type BusinessDayConventionEnum = { tag: string };
export type DayOfWeek = { tag: string };
export type PeriodEnum = { tag: string };
export type DayTypeEnum = { tag: string };
export type StubPeriodTypeEnum = { tag: string };
export type RollConventionEnum = { tag: string };
`;

    const outputPath = path.join(this.outputDir, 'core', 'interfaces.ts');
    fs.writeFileSync(outputPath, output);
    console.log(`   ✓ core/interfaces.ts`);
  }

  private generateCoreIndex(): void {
    const output = `// core/index.ts
// Re-exports all core types
// DO NOT EDIT - Generated by generate-canton-api.ts

export * from './primitives';
export * from './interfaces';
`;

    const outputPath = path.join(this.outputDir, 'core', 'index.ts');
    fs.writeFileSync(outputPath, output);
    console.log(`   ✓ core/index.ts`);
  }

  private generateProjectApi(): void {
    const output = this.buildProjectApi();
    const outputPath = path.join(this.outputDir, `${this.projectName}-api.ts`);
    fs.writeFileSync(outputPath, output);
    console.log(`   ✓ ${this.projectName}-api.ts`);
  }

  private buildProjectApi(): string {
    let output = `// ${this.projectName}-api.ts
// ${this.projectName.charAt(0).toUpperCase() + this.projectName.slice(1)} Project API
// DO NOT EDIT - Generated by generate-canton-api.ts
//
// This file contains all workflows and operations available in the ${this.projectName} project.
// Import this file to interact with the Canton ledger.

import {
  Party, ContractId, Optional, Numeric, Time, Command, Contract, ExerciseResult
} from './core/primitives';
import {
  AccountKey, InstrumentKey, HoldingFactoryKey, Quantity, Id, Controllers,
  Lock, RoutedStep, HoldingStandard, Allocation, Approval
} from './core/interfaces';

// ═══════════════════════════════════════════════════════════════
// TEMPLATE IDS
// ═══════════════════════════════════════════════════════════════

export const TemplateIds = {
`;

    // Add all template IDs
    for (const module of this.modules) {
      output += `  ${module.qualifiedName}: '${module.templateId}',\n`;
    }
    output += `} as const;\n\n`;

    // Add workflows section
    output += `// ═══════════════════════════════════════════════════════════════
// WORKFLOWS
// ═══════════════════════════════════════════════════════════════
// Each workflow follows a request/response pattern:
// 1. Requester creates a Request/Proposal contract
// 2. Counterparty can Accept, Decline, or the requester can Withdraw
//
// Usage:
//   const cmd = CreateAccount.request({ custodian, owner });
//   await ledger.create(cmd.templateId, cmd.argument);
// ═══════════════════════════════════════════════════════════════

`;

    // Generate CreateAccount workflow
    output += this.generateCreateAccountWorkflow();

    // Generate Transfer workflow
    output += this.generateTransferWorkflow();

    // Generate CreditAccount workflow
    output += this.generateCreditAccountWorkflow();

    // Generate DvP workflow
    output += this.generateDvPWorkflow();

    // Add helper types
    output += `
// ═══════════════════════════════════════════════════════════════
// HOLDING TYPES
// ═══════════════════════════════════════════════════════════════

/**
 * Base holding representing asset ownership.
 */
export interface Holding {
  instrument: InstrumentKey;
  account: AccountKey;
  amount: Numeric;
  lock: Optional<Lock>;
  observers: Record<string, Party[]>;
}

/**
 * Fungible holding - can be merged and split.
 */
export interface Fungible extends Holding {}

/**
 * Transferable holding - can change ownership.
 */
export interface Transferable extends Holding {}

/**
 * Holding that is both fungible and transferable.
 * Most common type for liquid financial assets.
 */
export interface TransferableFungible extends Holding {}

// ═══════════════════════════════════════════════════════════════
// SETTLEMENT TYPES
// ═══════════════════════════════════════════════════════════════

/**
 * Settlement batch grouping multiple instructions.
 */
export interface Batch {
  instructor: Party;
  consenters: Party[];
  settlers: Party[];
  id: Id;
  description: string;
  contextId: Optional<Id>;
  routedStepsWithInstructionId: Array<{ step: RoutedStep; instructionId: Id }>;
  settlementTime: Optional<Time>;
}

/**
 * Single settlement instruction.
 */
export interface Instruction {
  instructor: Party;
  consenters: Party[];
  settlers: Party[];
  batchId: Id;
  id: Id;
  routedStep: RoutedStep;
  settlementTime: Optional<Time>;
  allocation: Allocation;
  approval: Approval;
  signedSenders: Party[];
  signedReceivers: Party[];
  observers: Record<string, Party[]>;
}

// ═══════════════════════════════════════════════════════════════
// ACCOUNT TYPES
// ═══════════════════════════════════════════════════════════════

/**
 * Account for holding assets.
 */
export interface Account {
  custodian: Party;
  owner: Party;
  lock: Optional<Lock>;
  controllers: Controllers;
  id: Id;
  description: string;
  holdingFactory: HoldingFactoryKey;
  observers: Record<string, Party[]>;
}

// ═══════════════════════════════════════════════════════════════
// INSTRUMENT TYPES
// ═══════════════════════════════════════════════════════════════

/**
 * Financial instrument definition.
 */
export interface Instrument {
  depository: Party;
  issuer: Party;
  id: Id;
  version: string;
  holdingStandard: HoldingStandard;
  description: string;
  validAsOf: Time;
  observers: Record<string, Party[]>;
}
`;

    return output;
  }

  private generateCreateAccountWorkflow(): string {
    return `/**
 * ┌─────────────────────────────────────────────────────────────┐
 * │  CREATE ACCOUNT WORKFLOW                                    │
 * ├─────────────────────────────────────────────────────────────┤
 * │  Request a new account from a custodian.                    │
 * │                                                             │
 * │  Flow:                                                      │
 * │    1. Owner calls CreateAccount.request()                   │
 * │    2. Custodian sees the request                            │
 * │    3. Custodian calls CreateAccount.accept() or .decline()  │
 * │    4. If accepted, Account contract is created              │
 * └─────────────────────────────────────────────────────────────┘
 */
export namespace CreateAccount {

  /** Request contract created when owner requests an account */
  export interface Request {
    custodian: Party;
    owner: Party;
  }

  /** Parameters for accepting an account request */
  export interface AcceptParams {
    /** Human-readable label for the account */
    label: string;
    /** Account description */
    description: string;
    /** Contract ID of the account factory to use */
    accountFactoryCid: ContractId<unknown>;
    /** Key identifying the holding factory */
    holdingFactory: HoldingFactoryKey;
    /** Additional observer parties */
    observers: Party[];
  }

  /**
   * Create a request for a new account.
   * The owner requests an account from a custodian.
   */
  export function request(params: Request): Command<Request> {
    return {
      templateId: TemplateIds.Workflow_CreateAccount_Request,
      argument: params
    };
  }

  /**
   * Accept an account creation request.
   * Only the custodian can accept.
   */
  export function accept(
    contractId: ContractId<Request>,
    params: AcceptParams
  ): Command<AccountKey> {
    return {
      templateId: TemplateIds.Workflow_CreateAccount_Request,
      choice: 'Accept',
      contractId: contractId as string,
      argument: params
    };
  }

  /**
   * Decline an account creation request.
   * Only the custodian can decline.
   */
  export function decline(contractId: ContractId<Request>): Command<void> {
    return {
      templateId: TemplateIds.Workflow_CreateAccount_Request,
      choice: 'Decline',
      contractId: contractId as string,
      argument: {}
    };
  }

  /**
   * Withdraw an account creation request.
   * Only the original requester (owner) can withdraw.
   */
  export function withdraw(contractId: ContractId<Request>): Command<void> {
    return {
      templateId: TemplateIds.Workflow_CreateAccount_Request,
      choice: 'Withdraw',
      contractId: contractId as string,
      argument: {}
    };
  }
}

`;
  }

  private generateTransferWorkflow(): string {
    return `/**
 * ┌─────────────────────────────────────────────────────────────┐
 * │  TRANSFER WORKFLOW                                          │
 * ├─────────────────────────────────────────────────────────────┤
 * │  Request to transfer assets to another account.             │
 * │                                                             │
 * │  Flow:                                                      │
 * │    1. Receiver calls Transfer.request()                     │
 * │    2. Current owner sees the request                        │
 * │    3. Owner calls Transfer.accept() with holdingCid         │
 * │    4. Assets move to receiver's account                     │
 * └─────────────────────────────────────────────────────────────┘
 */
export namespace Transfer {

  /** Request contract for asset transfer */
  export interface Request {
    receiverAccount: AccountKey;
    instrument: InstrumentKey;
    amount: Numeric;
    currentOwner: Party;
  }

  /** Parameters for accepting a transfer request */
  export interface AcceptParams {
    holdingCid: ContractId<Holding>;
  }

  export function request(params: Request): Command<Request> {
    return {
      templateId: TemplateIds.Workflow_Transfer_Request,
      argument: params
    };
  }

  export function accept(
    contractId: ContractId<Request>,
    holdingCid: ContractId<Holding>
  ): Command<ContractId<Holding>> {
    return {
      templateId: TemplateIds.Workflow_Transfer_Request,
      choice: 'Accept',
      contractId: contractId as string,
      argument: { holdingCid }
    };
  }

  export function decline(contractId: ContractId<Request>): Command<void> {
    return {
      templateId: TemplateIds.Workflow_Transfer_Request,
      choice: 'Decline',
      contractId: contractId as string,
      argument: {}
    };
  }

  export function withdraw(contractId: ContractId<Request>): Command<void> {
    return {
      templateId: TemplateIds.Workflow_Transfer_Request,
      choice: 'Withdraw',
      contractId: contractId as string,
      argument: {}
    };
  }
}

`;
  }

  private generateCreditAccountWorkflow(): string {
    return `/**
 * ┌─────────────────────────────────────────────────────────────┐
 * │  CREDIT ACCOUNT WORKFLOW                                    │
 * ├─────────────────────────────────────────────────────────────┤
 * │  Request to credit (mint) assets into an account.           │
 * │  Typically used by issuers to create new holdings.          │
 * └─────────────────────────────────────────────────────────────┘
 */
export namespace CreditAccount {

  export interface Request {
    account: AccountKey;
    instrument: InstrumentKey;
    amount: Numeric;
  }

  export function request(params: Request): Command<Request> {
    return {
      templateId: TemplateIds.Workflow_CreditAccount_Request,
      argument: params
    };
  }

  export function accept(contractId: ContractId<Request>): Command<ContractId<Holding>> {
    return {
      templateId: TemplateIds.Workflow_CreditAccount_Request,
      choice: 'Accept',
      contractId: contractId as string,
      argument: {}
    };
  }

  export function decline(contractId: ContractId<Request>): Command<void> {
    return {
      templateId: TemplateIds.Workflow_CreditAccount_Request,
      choice: 'Decline',
      contractId: contractId as string,
      argument: {}
    };
  }

  export function withdraw(contractId: ContractId<Request>): Command<void> {
    return {
      templateId: TemplateIds.Workflow_CreditAccount_Request,
      choice: 'Withdraw',
      contractId: contractId as string,
      argument: {}
    };
  }
}

`;
  }

  private generateDvPWorkflow(): string {
    return `/**
 * ┌─────────────────────────────────────────────────────────────┐
 * │  DVP (DELIVERY VS PAYMENT) WORKFLOW                         │
 * ├─────────────────────────────────────────────────────────────┤
 * │  Atomic exchange of two assets between counterparties.      │
 * │  Either both legs settle or neither does.                   │
 * └─────────────────────────────────────────────────────────────┘
 */
export namespace DvP {

  export interface Proposal {
    recQuantity: Quantity;
    payQuantity: Quantity;
    proposer: Party;
    counterparty: Party;
    routeProviderCid: ContractId<unknown>;
    settlementFactoryCid: ContractId<unknown>;
    id: string;
  }

  export interface AcceptResult {
    batchCid: ContractId<Batch>;
    instruction1Cid: ContractId<Instruction>;
    instruction2Cid: ContractId<Instruction>;
  }

  export function propose(params: Proposal): Command<Proposal> {
    return {
      templateId: TemplateIds.Workflow_DvP_Proposal,
      argument: params
    };
  }

  export function accept(contractId: ContractId<Proposal>): Command<AcceptResult> {
    return {
      templateId: TemplateIds.Workflow_DvP_Proposal,
      choice: 'Accept',
      contractId: contractId as string,
      argument: {}
    };
  }

  export function decline(contractId: ContractId<Proposal>): Command<void> {
    return {
      templateId: TemplateIds.Workflow_DvP_Proposal,
      choice: 'Decline',
      contractId: contractId as string,
      argument: {}
    };
  }

  export function withdraw(contractId: ContractId<Proposal>): Command<void> {
    return {
      templateId: TemplateIds.Workflow_DvP_Proposal,
      choice: 'Withdraw',
      contractId: contractId as string,
      argument: {}
    };
  }
}

`;
  }
}

// === MAIN ===

function main(): void {
  const args = process.argv.slice(2);

  if (args.length < 2) {
    console.error('Usage: npx ts-node generate-canton-api.ts <daml-js-dir> <output-dir> [project-name]');
    console.error('Example: npx ts-node generate-canton-api.ts ../daml-js . vault');
    process.exit(1);
  }

  const damlJsDir = path.resolve(args[0]);
  const outputDir = path.resolve(args[1]);
  const projectName = args[2] || 'project';

  if (!fs.existsSync(damlJsDir)) {
    console.error(`Error: daml-js directory not found: ${damlJsDir}`);
    process.exit(1);
  }

  const generator = new CantonApiGenerator(damlJsDir, outputDir, projectName);
  generator.generate();
}

main();
