package com.moonsonglabs.daml.devcontainer

import com.intellij.openapi.components.Service
import com.intellij.openapi.components.service
import com.intellij.openapi.project.Project
import com.intellij.openapi.vfs.LocalFileSystem
import com.moonsonglabs.daml.workspace.DamlWorkspaceService
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.exists
import kotlin.io.path.name
import kotlin.io.path.readText
import kotlin.io.path.writeText

@Service(Service.Level.PROJECT)
class DevcontainerTemplateInstaller(private val project: Project) {

    data class InstallResult(val written: List<Path>, val skipped: List<Path>, val root: Path?)

    fun installOrUpdate(): InstallResult {
        val root = DamlWorkspaceService.getInstance(project).projectRoot() ?: return InstallResult(emptyList(), emptyList(), null)
        val devcontainerDir = root.resolve(".devcontainer")
        devcontainerDir.createDirectories()

        val written = mutableListOf<Path>()
        val skipped = mutableListOf<Path>()
        for (template in TEMPLATES) {
            val target = devcontainerDir.resolve(template.targetName)
            val content = readResource(template.resourcePath)
            if (target.exists() && !target.readText().contains(MARKER)) {
                skipped.add(target)
                val alternate = devcontainerDir.resolve("canton-jetbrains-${target.name}")
                alternate.writeText(content, StandardCharsets.UTF_8)
                written.add(alternate)
            } else {
                target.writeText(content, StandardCharsets.UTF_8)
                written.add(target)
            }
        }
        LocalFileSystem.getInstance().refreshIoFiles((written + skipped).map { it.toFile() })
        return InstallResult(written, skipped, root)
    }

    fun hasPreparedDevcontainer(): Boolean {
        val root = DamlWorkspaceService.getInstance(project).projectRoot() ?: return false
        val devcontainerJson = root.resolve(".devcontainer/devcontainer.json")
        return devcontainerJson.exists() && devcontainerJson.readText().contains(MARKER)
    }

    private fun readResource(path: String): String {
        val stream = javaClass.getResourceAsStream(path) ?: error("Missing devcontainer resource: $path")
        return stream.readBytes().toString(StandardCharsets.UTF_8)
    }

    companion object {
        const val MARKER = "Generated by Canton JetBrains Plugin"

        private data class Template(val resourcePath: String, val targetName: String)

        private val TEMPLATES = listOf(
            Template("/devcontainer/devcontainer.json", "devcontainer.json"),
            Template("/devcontainer/Dockerfile", "Dockerfile")
        )

        fun getInstance(project: Project): DevcontainerTemplateInstaller = project.service()
    }
}
